### ISSUE TITLE
No "edit" button

### ISSUE THREAD

**Issue by flo-x** [flexdash/node-red-flexdash#11]
I just installed FlexDash in a fresh Node Red installation in Windows 10, put a couple of FlexDash widgets in a flow, but I do not see the "Edit" toggle, so can't enter edit mode. The rest of it works fine - widgets work as expected, the toggle "Dark mode" is there and works.

I feel like I'm missing something obvious...

Thanks!

**Comment by tve** [comment]
Yup! The editing now all happens in the Node-RED flow editor.
If you have issues, please post to the Node-RED forum, lots more help there.

**Comment by flo-x** [comment]
Ah, thanks !!! :)
