### ISSUE TITLE
feature request: dashboard config option to set dark mode by default

### ISSUE THREAD

**Issue by parasaurolophus** [flexdash/node-red-flexdash#7]
Please add an option to the dashboard config node in the Node-RED editor to specify dark / light mode as the default. Not only would this be a desirable enhancement in itself, it would also provide a work around for the issue preventing `?theme=dark` query string parameters from having an effect when using the Node-RED web server to host FlexDash; i.e. the original URL is rewritten by the Node-RED web server such that the query string is eliminated, apparently before FexDash acts on it.

**Comment by tve** [comment]
It's on the list... BTW, as long as you have a trailing slash on the URL there is no redirect and thus the query string is not eliminated. E.g. `http://example.com/flexdash/?theme=dark`, note the `/` before the `?`.
Please use the Node-RED forum for features/discussions/problems/...
